services:
  backend:
    build: ./modules/services/classroom-backend
    ports:
      - 3001:3001
    depends_on:
      - backend-db
    environment:
      - DATABASE_HOST=backend-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=classroom
      - DATABASE_PASSWORD=classroom
      - DATABASE_NAME=classroom

  backend-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/backend-db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=classroom
      - POSTGRES_USER=classroom
      - POSTGRES_DB=classroom

  admin:
    build:
      context: ./modules/apps/classroom-admin-web
      args:
        - HOST_BASE_URL=/admin
        - API_BASE_URL=http://localhost:8000/api
    ports:
      - 8001:8001
    depends_on:
      - backend

  gateway:
    build: ./modules/services/classroom-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./data/gateway:/app/classroom
    depends_on:
      - backend
      - admin
